# Config file for shoutout app, Learn a new language everyday!

Main:
    darkMode: true
    selectedlang: "english" # current language selected
    selectedword: "Shoutout" # current word selected
    KID: 333233
#    complexity: "easy" # easy, normal, hard, wildcard
#    apionline: false # option for turning on full API access, not using language caches
    configversion: "1-beta" # Simple increment of 1, 2, 3, if in beta use "beta-" before

UI:
    lastDay: ""
#    lastTime: ""
    LOL: 123456789
    lastComplexity: 3

Other:
    custom_languages:
        - "Example"
