# Config file for shoutout app, Learn a new language everyday!

- Main:
    darkMode: true
    onlinentp: true
    selectedlang: "" # current language selected
    complexity: "wildcard" # simple, basic, complex, wildcard
    apionline: false # option for turning on full API access, not using language caches
